---
- name: Update DNF configuration
  copy:
    src: files/dnf.conf
    dest: /etc/dnf/dnf.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Clear cache
  command: dnf clean all
  become: yes
  register: dnf_clean
  changed_when: '"\n0 files removed" not in dnf_clean.stdout'

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
  become: yes

- name: Install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present
  become: yes
  tags: ["dnf-automatic"]

- name: Enable and start dnf-automatic.timer
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes
  become: yes
  tags: ["dnf-automatic"]
