---
- name: Add Docker CE gpg key
  rpm_key:
    key: https://download.docker.com/linux/fedora/gpg
    state: present
  become: yes

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install Docker Engine
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Start the Docker daemon on boot
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Ensure group docker exists
  group:
    name: docker
    state: present
  become: yes

- name: "Add {{ lookup('env', 'USER') }} to docker group"
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: yes
