---
- name: Enable OpenH264 repository
  command: dnf config-manager --set-enabled fedora-cisco-openh264
  become: yes

- name: Install OpenH264 plugin
  dnf:
    name:
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    state: present
  become: yes
