---
- name: Add VS Code gpg key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Add VS Code repository
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: Install VS Code
  dnf:
    name: code
    state: present
    update_cache: yes
  become: yes

- name: Set fs.inotify.max_user_watches to 524288
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
  become: yes

- name: Install VS Code extensions
  command: "code --install-extension {{ item }}"
  loop:
    - redhat.ansible
    - aaron-bond.better-comments
    - streetsidesoftware.code-spell-checker
    - deerawan.vscode-dash
    - ms-azuretools.vscode-docker
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - wix.vscode-import-cost
    - oderwat.indent-rainbow
    - ms-vsliveshare.vsliveshare
    - esbenp.prettier-vscode
    - ms-vscode-remote.vscode-remote-extensionpack
    - wayou.vscode-todo-highlight
    - vscode-icons-team.vscode-icons
  register: install_extension
  changed_when: "'already installed' not in install_extension.stdout"
